<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?php View::partial('subnav/usuario/principal', FALSE, array('id'=>$usuario->id)); ?>

    <?php echo DwForm::open(); ?>
        
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-6">
                        <?php echo DwForm::text('usuario.nombre', array('class'=>' input-readonly'), $usuario->persona->nombre, 'Nombre'); ?>                        
                    </div>
                    <div class="col-md-6">
                        <?php echo DwForm::text('usuario.nombre', array('class'=>' input-readonly'), $usuario->persona->apellido, 'Apellido'); ?>                        
                    </div>
                </div>
                <div class="row">  
                    <div class="col-md-6">
                        <?php echo DwForm::text('usuario.login', array('class'=>'input-lower input-readonly'), $usuario->login, 'Usuario'); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo DwForm::oneSelect('usuario.perfil', $usuario->perfil->perfil, array('class'=>' input-readonly'), 'Perfil'); ?>
                    </div>
                </div>  
                <div class="row">  
                    <div class="col-md-6">
                        <?php echo DwForm::text('usuario.usuario_at', array('class'=>'input-lower input-readonly'), $usuario->usuario_at, 'Creado'); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo DwForm::text('usuario.usuario_in', array('class'=>'input-lower input-readonly'), $usuario->usuario_in, 'Modificado'); ?>
                    </div>
                </div>                        
            </div>
          
            <div class="col-md-4 text-right hidden-xs hidden-sm">
                <div class="col-md-6 profile-picture text-center text-middle shadow-dark" style="margin-top: 5px">
                    <?php echo DwHtml::img("upload/personas/vleon.jpeg", $usuario->nombre.' '.$usuario->apellido, array('id'=>'img-persona')); ?>
                </div>
            </div>
        </div>
    
    <?php echo DwForm::close(); ?>
    
    <hr />
        
    <div class="container-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th>FECHA</th>
                    <th>HORA</th>
                    <th>IP</th>
                    <th>TIPO</th>
                </tr>
            </thead>
            <tbody>                
                <?php if($accesos->items) { ?>
                <?php foreach($accesos->items as $acceso): ?>
                <tr>
                    <td><?php echo $accesos->counter; ?></td>
                    <td><?php echo date("Y-m-d", strtotime($acceso->acceso_at)); ?></td>
                    <td><?php echo date("H:i:s", strtotime($acceso->acceso_at)); ?></td>
                    <td><?php echo $acceso->ip; ?></td>
                    <td><?php echo ($acceso->tipo_acceso == Acceso::ENTRADA) ? '<span class="label label-success">Entrada</span>' : '<span class="label label-danger">Salida</span>'; ; ?></td>
                </tr>
                <?php $accesos->counter++; ?>
                <?php endforeach; ?>
                <?php } ?>
            </tbody>
        </table>
        
        <?php View::partial('paginators/default', FALSE, array('page'=>$accesos, 'url'=>"sistema/usuarios/accesos/$key/")); ?>

    </div>

    <div class="row">
        <div class="form-actions">                
            <div class="text-left">
                <?php echo DwButton::back(); ?>                    
            </div>
        </div>
    </div>

</div>