<?php View::flash(); ?>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php View::partial('subnav/usuario/principal', FALSE, array('id'=>$usuario->id)); ?>
    
    <?php echo DwForm::open(); ?>
    
    <ul class="nav nav-tabs hidden-xs">
        <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
        <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
        <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
    </ul>
    <ul class="nav nav-pills nav-stacked visible-xs">    
        <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
        <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
        <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
    </ul>

    <div class="tab-content">
        
        <div class="tab-pane active" id="tab1">

                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <?php echo DwForm::text('persona.nombre', array('class'=>' input-required'), $usuario->persona->nombre, 'Nombre'); ?>                        
                            </div>
                            <div class="col-md-6">
                                <?php echo DwForm::text('persona.apellido', array('class'=>' input-required'), $usuario->persona->apellido, 'Apellido'); ?>                        
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <?php echo DwForm::text('persona.nuip', array('class'=>' input-required'), $usuario->persona->nuip, $usuario->persona->tipo_nuip->tipo_nuip); ?>                        
                            </div>
                            <div class="col-md-3">
                                <?php echo DwForm::text('persona.telefono', array('class'=>' input-required'), $usuario->persona->telefono, 'Teléfono'); ?>                        
                            </div>
                            <div class="col-md-3">
                                <?php echo DwForm::text('persona.celular', array('class'=>' input-required'), $usuario->persona->celular, 'Celular'); ?>                        
                            </div>
                        </div>   
                        <div class="row">
                            <div class="col-md-6">                    
                                <?php echo DwForm::text('persona.fotografia', array('class'=>'input-required'), $usuario->persona->fotografia, 'Archivo de Fotografía'); ?>
                            </div>                   
                        </div>                   
                    </div>                    
                    <div class="col-md-4 text-center hidden-xs hidden-sm">
                        <div class="col-md-6 profile-picture text-center text-middle shadow-dark" style="margin-top: 5px">
                            <?php echo DwHtml::img("upload/personas/".$usuario->persona->fotografia, $usuario->persona->nombre.' '.$usuario->persona->apellido, array('id'=>'img-persona')); ?>
                        </div>
                    </div>
                </div>
                
            <div class="row">
                <div class="form-actions">
                    <?php echo DwForm::nextTab(); ?>
                </div>
            </div>
        </div>

        <div class="tab-pane" id="tab2">
                
                <div class="row">
                    <div class="col-md-4">
                        <?php echo DwForm::text('usuario.login', array('class'=>'input-lower input-required'), $usuario->login, 'Usuario'); ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo DwForm::oneSelect('usuario.perfil', $usuario->perfil->perfil, array('class'=>' input-required'), 'Perfil'); ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo DwForm::oneSelect('usuario.tema', $usuario->tema, array('class'=>' input-required'), 'Apariencia'); ?>
                    </div>
                </div>

                <div class="row">                    
                    <div class="col-md-2">
                        <?php echo DwForm::text('usuario.datagrid', array('class'=>'input-lower input-required'), $usuario->datagrid, 'Registros por página'); ?>
                    </div>          
                    <div class="col-md-2">
                        <?php echo DwForm::oneSelect('usuario.app_ajax', ($usuario->app_ajax==1) ? 'On' : 'Off', array('class'=>' input-required'), 'App con AJAX'); ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo DwForm::text('usuario.pool', array('class'=>'input-lower input-required'), $usuario->pool, 'Pool'); ?>
                    </div>                               
                    <div class="col-md-4">
                        <?php echo DwForm::email('usuario.email', array('class'=>' input-required'), $usuario->email, 'Email'); ?>
                    </div>
                </div>
            
        </div>
        
        <div class="tab-pane" id="tab3">
            
            <div class="row fileupload-buttonbar">
                <div class="col-md-6" style="margin-bottom: 20px;">
                    <div class="row">
                        <div class="col-md-4">
                            <?php echo DwForm::upload('fotografia', array('data-to'=>PUBLIC_PATH.'sistema/usuarios/upload/', 'data-size'=>5000000, 'data-files'=>'images', 'data-success'=>'loadImg'), 'Fotografía'); ?>
                        </div>

                        <div class="col-md-4">
                            <div class="picture-profile text-center text-middle shadow-dark" style="margin: 5px auto 0px;">
                                <?php echo DwHtml::img("upload/personas/".$usuario->persona->fotografia, "Fotografía", array('id'=>'img-usuario')); ?>
                            </div>
                        </div>   
                    </div>
                </div>
            </div>

            <?php echo DwForm::hidden('usuario.fotografia', NULL, $usuario->fotografia); ?>
            
        </div>        
        
    </div>
    
    <div class="row">
        <div class="form-actions">
            <?php echo DwForm::send('Editar usuario'); ?>
            <?php echo DwForm::cancel(); ?>
            <?php echo DwForm::focus('usuario.tipo_nuip_id'); ?>            
        </div>
    </div>
   
    <?php echo DwForm::close(); ?>
    
</div>

<script type="text/javascript">
    
    function loadImg(result, input) {
        $("#usuario_fotografia").val(result.name);
        $("#img-usuario").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);                
    }
    
</script>