<?php View::flash(); ?>

<script type='text/javascript'>

    $(document).ready(function(){
        $("#perfil_id").change(function(){
            var perfil_id   =   $('#perfil_id').val();
            $.ajax({    
                  type: "POST",
                  url: "<?php echo PUBLIC_PATH . 'sistema/perfiles/getUsuarios/'; ?>",
                  data: "perfil_id=" + perfil_id,
                  success: function(html){
                    $("#div_usuario").html(html);
                    $("#div_usuario").focus;    
                 }
            });
        });
    }); 

</script> 

<script type="text/javascript">
    $('#logo').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>config/empresa/upload/',
        dataType: 'json',
        maxFileSize: 2000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#empresa_logo").val(result.name);
                    $("#img-empresa").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/empresa/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?php View::partial('subnav/empresa/principal', FALSE, array('id'=>$empresa->id)); ?>

    <?php echo DwForm::openMultipart(); ?>
        
    <ul class="nav nav-tabs hidden-xs">
        <li class="active"><a href="#tab1" data-toggle="tab">Información general</a></li>
        <li><a href="#tab2" data-toggle="tab">Representante Legal</a></li>     
        <li><a href="#tab3" data-toggle="tab">Logo</a></li>     
    </ul>
    
    <div class="tab-content">

        <div class="tab-pane active" id="tab1">
                
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::text('empresa.razon_social', array('class'=>'input-required'), $empresa->razon_social, "Nombre o Razón Social"); ?>                        
                </div>
                <div class="col-md-2">
                    <?php echo DwForm::text('empresa.siglas', array('class'=>'input-required'), $empresa->siglas, 'Siglas'); ?>
                </div>  
                <div class="col-md-4">
                    <?php echo DwForm::text('empresa.nuip', array('class'=>'input-required'), $empresa->nuip, $empresa->tipo_nuip->tipo_nuip); ?>
                </div>                      
            </div>   
            <div class="row">  
                <div class="col-md-4">
                    <?php echo DwForm::text('empresa.nit', array('class'=>'input-required'), $empresa->nit, "Nit"); ?>                        
                </div>                            
                <div class="col-md-4">
                    <?php echo DwForm::text('empresa.telefono', array('class'=>'input-required'), $empresa->telefono, 'Teléfono'); ?>
                </div>                                 
                <div class="col-md-4">
                        <?php echo DwForm::text('empresa.fax', array('class'=>'input-required'), $empresa->fax, 'Fax'); ?>
                </div>                                
            </div>  
            <div class="row">                           
                <div class="col-md-4">
                    <?php echo DwForm::email('empresa.email', array('class'=>'input-email input-required mask-email'), $empresa->email, 'Email'); ?>
                </div>                             
                <div class="col-md-6">
                    <?php echo DwForm::url('empresa.pagina_web', array('class'=>' input-required'), $empresa->pagina_web, 'Página Web'); ?>
                </div>   
            </div>    
            
            <?php echo DwForm::hiddenKey('empresa.usuario_id', $empresa->usuario_id); ?>
            <?php echo DwForm::hiddenKey('empresa.tipo_nuip_id', $empresa->tipo_nuip_id); ?>

            <div class="row">
                <div class="form-actions">
                    <?php echo DwButton::nextTab(); ?>
                </div>
            </div>

        </div>

        <div class="tab-pane" id="tab2">
                
            <div class="row">
                <div class="col-md-8">
                    <?php echo DwForm::dbSelect('perfil_id', 'perfil', array('perfil','find', 'order: perfil ASC'),$empresa->usuario->perfil->perfil,NULL,NULL,'Perfil del Representante') ?>
                    <div id="div_usuario"></div> 
                </div>  
                <div class="col-md-4 text-right hidden-xs hidden-sm">
                    <div class="col-md-6 profile-picture text-center text-middle shadow-dark" style="margin-top: 5px">
                        <?php echo DwHtml::img("upload/personas/".$empresa->usuario->persona->fotografia, $empresa->usuario->persona->nombre.' '.$empresa->usuario->persona->apellido, array('id'=>'img-persona')); ?>
                    </div>
                </div> 
            </div>  

            <div class="row">
                <div class="form-actions">
                    <?php echo DwButton::prevTab(); ?> 
                    <?php echo DwButton::nextTab(); ?>
                </div>
            </div>

        </div>
        
        <div class="tab-pane" id="tab3">     
            <div class="row fileupload-buttonbar">

                <div class="span2">
                    <span class="btn btn-success fileinput-button">
                        <i class="icon-plus icon-white"></i>
                        <span>Cargar logo...</span>
                        <input id="logo" type="file" name="logo">
                    </span>
                </div>

                <div id="upload-progress" class="span4 fileupload-progress fade">
                    <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                        <div class="bar" style="width:0%;"></div>
                    </div>
                </div>

                <div class="span5 dw-text-right">
                    <div class="span5 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                        <?php echo DwHtml::img('upload/empresa/'.$empresa->logo, $empresa->razon_social, array('id'=>'img-empresa')); ?>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="form-actions">
                    <?php echo DwButton::prevTab(); ?> 
                </div>
            </div>
        </div> 

    </div>

    <div class="row">
        <div class="form-actions">
            <?php echo DwForm::send('Actualizar Empresa'); ?>
            <?php echo DwForm::cancel(); ?>
            <?php echo DwForm::focus('empresa.razon_social'); ?>            
        </div>
    </div>

    <?php echo DwForm::close(); ?>

</div>